# Generated by Django 2.0.1 on 2018-01-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180107_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
