# Generated by Django 2.0.1 on 2018-01-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180110_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id1', models.IntegerField()),
                ('User_id2', models.IntegerField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'friend',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_show',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='article',
            name='is_shown',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], default='Y', max_length=1),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='activatied',
            field=models.BooleanField(default=True),
        ),
    ]
