# Generated by Django 2.0.1 on 2018-01-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180113_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
