# Generated by Django 2.0.1 on 2018-01-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180113_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='User_id1',
            new_name='user_id1',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='User_id2',
            new_name='user_id2',
        ),
        migrations.AlterField(
            model_name='article',
            name='is_shown',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
    ]
