# Generated by Django 2.0.1 on 2018-01-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180113_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-modified_time']},
        ),
        migrations.AlterField(
            model_name='user',
            name='activatied',
            field=models.BooleanField(default=False),
        ),
    ]
