# Generated by Django 2.0.1 on 2018-01-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180115_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
