# Generated by Django 2.0.1 on 2018-01-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180115_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time_stamp']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-time_stamp']},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
