# Generated by Django 2.0.1 on 2018-01-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180115_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/images/default.png', upload_to='images'),
        ),
    ]
